[workspace]
resolver = "2"
members = [
    "compiler/diagnostics",
    "compiler/lexer",
    "compiler/ast",
    "compiler/parser",
    "compiler/resolve",
    "compiler/types",
    "compiler/ir",
    "compiler/ownership",
    "compiler/driver",
    "compiler/backend",
    "tools/cli",
    "tools/fmt",
    "tools/lsp",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[profile.release]
debug = false
