/* Tarn internal runtime ABI v0: Linux x86_64, System V C ABI. */
#define _POSIX_C_SOURCE 200809L
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <math.h>

typedef struct { uint64_t len; unsigned char bytes[]; } TarnString;
/* Owned string pointers are unique. Literals allocate; moves transfer ownership. */
TarnString *tarn_rt_string(const unsigned char *data, uint64_t len) {
    if (len > SIZE_MAX - sizeof(TarnString)) abort();
    TarnString *s = malloc(sizeof(TarnString) + len);
    if (!s) abort();
    s->len = len;
    memcpy(s->bytes, data, len);
    return s;
}
void tarn_rt_drop_string(TarnString *s) {
    /* Opt-in compiler test observation, never a user destructor hook. */
    if (getenv("TARN_TRACE_DROPS")) { flockfile(stderr); fputs("drop:", stderr); fwrite(s->bytes, 1, s->len, stderr); fputc('\n', stderr); funlockfile(stderr); }
    free(s);
}
void tarn_rt_print_i64(int64_t v) { printf("%" PRId64 "\n", v); }
void tarn_rt_print_u64(uint64_t v) { printf("%" PRIu64 "\n", v); }
void tarn_rt_print_f64(double v) { printf("%.17g\n", v); }
void tarn_rt_print_bool(uint8_t v) { puts(v ? "true" : "false"); }
void tarn_rt_print_string(const TarnString *s) { fwrite(s->bytes, 1, s->len, stdout); fputc('\n', stdout); }
_Noreturn void tarn_rt_panic(const TarnString *s) {
    fputs("panic: ", stderr); fwrite(s->bytes, 1, s->len, stderr); fputc('\n', stderr); fflush(NULL); abort();
}
_Noreturn void tarn_rt_fault(void) { fputs("panic: checked arithmetic or bounds failure\n", stderr); fflush(NULL); abort(); }

float tarn_rt_rem_f32(float a, float b) { return fmodf(a, b); }
double tarn_rt_rem_f64(double a, double b) { return fmod(a, b); }

/* A closure environment header holds an internal, compiler-generated thunk.
 * Borrowed stack environments use a null thunk. Destruction and consumption
 * bodies are post-drop functions; their thunk releases owned storage. */
void *tarn_rt_env_alloc(uint64_t size) {
    void *p = malloc((size_t)size);
    if (!p) abort();
    return p;
}
void tarn_rt_env_free(void *p) { free(p); }
void tarn_rt_env_drop(void *p) {
    if (!p) return;
    void (*drop)(void *);
    memcpy(&drop, p, sizeof(drop));
    if (drop) drop(p);
}

/* Private 11A task ABI. Worker/result adapters are generated by the compiler;
 * this record has no knowledge of Tarn types or resource layouts. */
#include <pthread.h>
typedef void (*TarnTaskWorker)(void *, void *, void *);
typedef void (*TarnTaskResultDrop)(void *);
typedef struct {
    pthread_t thread;
    TarnTaskWorker worker;
    TarnTaskResultDrop drop_result;
    void *code;
    void *environment;
    void *result;
    unsigned initialized;
    unsigned joined;
} TarnTask;

static _Noreturn void tarn_task_fault(void) {
    fputs("panic: native task runtime fault\n", stderr);
    fflush(NULL);
    abort();
}

static void *tarn_task_entry(void *argument) {
    TarnTask *task = argument;
    task->worker(task->result, task->code, task->environment);
    task->initialized = 1;
    return NULL;
}

TarnTask *tarn_rt_task_spawn(TarnTaskWorker worker, TarnTaskResultDrop drop_result,
                           uint64_t result_size, void *code, void *environment) {
    if (!worker || !drop_result || result_size > 65536) tarn_task_fault();
    TarnTask *task = calloc(1, sizeof(*task));
    if (!task) tarn_task_fault();
    task->result = calloc(1, result_size ? (size_t)result_size : 1);
    if (!task->result) tarn_task_fault();
    task->worker = worker;
    task->drop_result = drop_result;
    task->code = code;
    task->environment = environment;
    if (pthread_create(&task->thread, NULL, tarn_task_entry, task)) tarn_task_fault();
    return task;
}

/* Borrowed result storage, valid until release; ownership transfers only when
 * generated join code moves its initialized value into caller storage. */
void *tarn_rt_task_wait(TarnTask *task) {
    if (!task || task->joined || pthread_equal(task->thread, pthread_self())) tarn_task_fault();
    if (pthread_join(task->thread, NULL)) tarn_task_fault();
    task->joined = 1;
    if (!task->initialized) tarn_task_fault();
    return task->result;
}

/* Called only after generated code has moved the result out. */
void tarn_rt_task_release(TarnTask *task) {
    if (!task || !task->joined || !task->initialized) tarn_task_fault();
    task->initialized = 0;
    free(task->result);
    free(task);
}

void tarn_rt_task_drop(TarnTask *task) {
    void *result = tarn_rt_task_wait(task);
    task->drop_result(result);
    tarn_rt_task_release(task);
}


/* Private 11C ABI: native mechanics only. Payloads and destruction belong to
 * verified Tarn values. No recursive locking, poisoning or ownership bit. */
#include <stdatomic.h>
#include <stdbool.h>
#include <limits.h>
typedef struct { pthread_mutex_t mutex; } TarnMutex;
static void tarn_sync_trace(const char *event) {
    if (getenv("TARN_TRACE_SYNC")) {
        flockfile(stderr); fprintf(stderr, "sync:%s\n", event); funlockfile(stderr);
    }
}
TarnMutex *tarn_rt_mutex_create(void) {
    TarnMutex *m = malloc(sizeof(*m));
    if (!m || pthread_mutex_init(&m->mutex, NULL)) abort();
    tarn_sync_trace("create");
    return m;
}
void tarn_rt_mutex_lock(TarnMutex *m) {
    if (pthread_mutex_lock(&m->mutex)) abort();
    tarn_sync_trace("lock");
}
void tarn_rt_mutex_unlock(TarnMutex *m) {
    tarn_sync_trace("unlock");
    if (pthread_mutex_unlock(&m->mutex)) abort();
}
void tarn_rt_mutex_destroy(TarnMutex *m) {
    if (pthread_mutex_destroy(&m->mutex)) abort();
    tarn_sync_trace("destroy");
    free(m);
}

/* Each scalar is real C11 atomic storage. All operations, including failure
 * of compare/exchange, are sequentially consistent. Never expose its address. */
#define TARN_ATOMIC(NAME, TYPE) \
typedef struct { _Atomic(TYPE) value; } TarnAtomic##NAME; \
TarnAtomic##NAME *tarn_rt_atomic_##NAME##_new(TYPE value) { \
    TarnAtomic##NAME *a = malloc(sizeof(*a)); if (!a) abort(); \
    atomic_init(&a->value, value); return a; \
} \
TYPE tarn_rt_atomic_##NAME##_load(TarnAtomic##NAME *a) { \
    return atomic_load_explicit(&a->value, memory_order_seq_cst); \
} \
void tarn_rt_atomic_##NAME##_store(TarnAtomic##NAME *a, TYPE value) { \
    atomic_store_explicit(&a->value, value, memory_order_seq_cst); \
} \
TYPE tarn_rt_atomic_##NAME##_swap(TarnAtomic##NAME *a, TYPE value) { \
    return atomic_exchange_explicit(&a->value, value, memory_order_seq_cst); \
} \
uint8_t tarn_rt_atomic_##NAME##_compare_exchange(TarnAtomic##NAME *a, TYPE expected, TYPE value) { \
    return atomic_compare_exchange_strong_explicit(&a->value, &expected, value, memory_order_seq_cst, memory_order_seq_cst); \
}
TARN_ATOMIC(bool, uint8_t)
TARN_ATOMIC(i32, int32_t)
TARN_ATOMIC(i64, int64_t)
TARN_ATOMIC(u32, uint32_t)
TARN_ATOMIC(u64, uint64_t)
TARN_ATOMIC(usize, uintptr_t)

/* Checked CAS loops: failed exchanges retry from the new observed value.
 * Overflow aborts without writing; no signed C overflow is ever evaluated. */
#define TARN_ATOMIC_SIGNED(NAME, TYPE, MINIMUM, MAXIMUM) \
TYPE tarn_rt_atomic_##NAME##_fetch_add(TarnAtomic##NAME *a, TYPE value) { \
    TYPE old = atomic_load_explicit(&a->value, memory_order_seq_cst); \
    for (;;) { \
        if ((value > 0 && old > MAXIMUM - value) || (value < 0 && old < MINIMUM - value)) tarn_rt_fault(); \
        TYPE next = old + value; \
        if (atomic_compare_exchange_strong_explicit(&a->value, &old, next, memory_order_seq_cst, memory_order_seq_cst)) return old; \
    } \
} \
TYPE tarn_rt_atomic_##NAME##_fetch_sub(TarnAtomic##NAME *a, TYPE value) { \
    TYPE old = atomic_load_explicit(&a->value, memory_order_seq_cst); \
    for (;;) { \
        if ((value > 0 && old < MINIMUM + value) || (value < 0 && old > MAXIMUM + value)) tarn_rt_fault(); \
        TYPE next = old - value; \
        if (atomic_compare_exchange_strong_explicit(&a->value, &old, next, memory_order_seq_cst, memory_order_seq_cst)) return old; \
    } \
}
#define TARN_ATOMIC_UNSIGNED(NAME, TYPE, MAXIMUM) \
TYPE tarn_rt_atomic_##NAME##_fetch_add(TarnAtomic##NAME *a, TYPE value) { \
    TYPE old = atomic_load_explicit(&a->value, memory_order_seq_cst); \
    for (;;) { \
        if (old > MAXIMUM - value) tarn_rt_fault(); \
        TYPE next = old + value; \
        if (atomic_compare_exchange_strong_explicit(&a->value, &old, next, memory_order_seq_cst, memory_order_seq_cst)) return old; \
    } \
} \
TYPE tarn_rt_atomic_##NAME##_fetch_sub(TarnAtomic##NAME *a, TYPE value) { \
    TYPE old = atomic_load_explicit(&a->value, memory_order_seq_cst); \
    for (;;) { \
        if (old < value) tarn_rt_fault(); \
        TYPE next = old - value; \
        if (atomic_compare_exchange_strong_explicit(&a->value, &old, next, memory_order_seq_cst, memory_order_seq_cst)) return old; \
    } \
}
TARN_ATOMIC_SIGNED(i32, int32_t, INT32_MIN, INT32_MAX)
TARN_ATOMIC_SIGNED(i64, int64_t, INT64_MIN, INT64_MAX)
TARN_ATOMIC_UNSIGNED(u32, uint32_t, UINT32_MAX)
TARN_ATOMIC_UNSIGNED(u64, uint64_t, UINT64_MAX)
TARN_ATOMIC_UNSIGNED(usize, uintptr_t, UINTPTR_MAX)
void tarn_rt_atomic_destroy(void *a) { free(a); }

/* Private blocking networking bridge. No ownership inference or public errno API. */
#include <errno.h>
#include <stddef.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <unistd.h>
typedef struct { uint8_t bytes[24]; } TarnNetAddr;
typedef struct { int32_t domain, code; int64_t value; TarnNetAddr address; } TarnNetRaw;
_Static_assert(sizeof(TarnNetRaw) == 40 && offsetof(TarnNetRaw, address) == 16, "network ABI");
static void net_init(TarnNetRaw *out) { memset(out, 0, sizeof(*out)); }
static void net_status(TarnNetRaw *out, int64_t value) { out->value = value; if (value < 0) out->code = errno; }
static void net_trace(const char *event, int fd) {
    if (getenv("TARN_TRACE_NET")) { flockfile(stderr); fprintf(stderr, "net:%s:%d\n", event, fd); funlockfile(stderr); }
}
static int net_native(const TarnNetAddr *address, struct sockaddr_storage *storage, socklen_t *len) {
    memset(storage, 0, sizeof(*storage));
    if (address->bytes[18] == 4) {
        struct sockaddr_in *a = (struct sockaddr_in *)storage;
        a->sin_family = AF_INET; memcpy(&a->sin_addr, address->bytes, 4); memcpy(&a->sin_port, address->bytes + 16, 2);
        *len = sizeof(*a); return AF_INET;
    }
    if (address->bytes[18] == 6) {
        struct sockaddr_in6 *a = (struct sockaddr_in6 *)storage;
        a->sin6_family = AF_INET6; memcpy(&a->sin6_addr, address->bytes, 16); memcpy(&a->sin6_port, address->bytes + 16, 2);
        uint32_t scope; memcpy(&scope, address->bytes + 20, 4); a->sin6_scope_id = ntohl(scope);
        *len = sizeof(*a); return AF_INET6;
    }
    errno = EINVAL; return -1;
}
static void net_address(TarnNetAddr *address, const struct sockaddr *sa) {
    memset(address, 0, sizeof(*address));
    if (sa->sa_family == AF_INET) {
        const struct sockaddr_in *a = (const struct sockaddr_in *)sa;
        memcpy(address->bytes, &a->sin_addr, 4); memcpy(address->bytes + 16, &a->sin_port, 2); address->bytes[18] = 4;
    } else if (sa->sa_family == AF_INET6) {
        const struct sockaddr_in6 *a = (const struct sockaddr_in6 *)sa;
        memcpy(address->bytes, &a->sin6_addr, 16); memcpy(address->bytes + 16, &a->sin6_port, 2); address->bytes[18] = 6;
        uint32_t scope = htonl(a->sin6_scope_id); memcpy(address->bytes + 20, &scope, 4);
    } else abort(); /* bridge only creates IPv4/IPv6 sockets */
}
void tarn_rt_net_resolve(TarnNetRaw *out, const TarnString *endpoint) {
    net_init(out);
    if (!endpoint->len || endpoint->len > 4096 || memchr(endpoint->bytes, 0, endpoint->len)) { out->domain = 2; out->code = EINVAL; return; }
    char *text = malloc(endpoint->len + 1); if (!text) abort();
    memcpy(text, endpoint->bytes, endpoint->len); text[endpoint->len] = 0;
    char *host = text, *port = NULL;
    if (*text == '[') { char *end = strchr(text, ']'); if (end && end[1] == ':') { *end = 0; host++; port = end + 2; } }
    else { char *colon = strrchr(text, ':'); if (colon && !memchr(text, ':', (size_t)(colon - text))) { *colon = 0; port = colon + 1; } }
    unsigned number = 0; int valid = port && *port;
    if (valid) for (const char *c = port; *c; c++) { if (*c < '0' || *c > '9' || number > 65535 / 10) { valid = 0; break; } number = number * 10 + (unsigned)(*c - '0'); if (number > 65535) { valid = 0; break; } }
    if (!valid) { free(text); out->domain = 2; out->code = EINVAL; return; }
    struct addrinfo hints = {0}, *list = NULL;
    hints.ai_family = AF_UNSPEC; hints.ai_socktype = SOCK_STREAM; hints.ai_flags = AI_NUMERICSERV | (!*host ? AI_PASSIVE : 0);
    int error = getaddrinfo(*host ? host : NULL, port, &hints, &list);
    if (error) { out->domain = error == EAI_SYSTEM ? 0 : 1; out->code = error == EAI_SYSTEM ? errno : error; free(text); return; }
    struct addrinfo *choice = NULL;
    for (struct addrinfo *a = list; a; a = a->ai_next) { if (a->ai_family == AF_INET) { choice = a; break; } if (!choice && a->ai_family == AF_INET6) choice = a; }
    if (choice) net_address(&out->address, choice->ai_addr); else { out->domain = 1; out->code = EAI_FAMILY; }
    freeaddrinfo(list); free(text);
}
void tarn_rt_net_socket(TarnNetRaw *out, const TarnNetAddr *address, uint8_t udp) {
    net_init(out); struct sockaddr_storage sa; socklen_t len;
    int family = net_native(address, &sa, &len);
    if (family < 0) { out->code = errno; return; }
    net_status(out, socket(family, udp ? SOCK_DGRAM : SOCK_STREAM, 0));
    if (!out->code) net_trace("open", (int)out->value);
}
void tarn_rt_net_bind(TarnNetRaw *out, int32_t fd, const TarnNetAddr *address) {
    net_init(out); struct sockaddr_storage sa; socklen_t len;
    if (net_native(address, &sa, &len) < 0) { out->code = errno; return; }
    net_status(out, bind(fd, (struct sockaddr *)&sa, len));
}
void tarn_rt_net_listen(TarnNetRaw *out, int32_t fd) { net_init(out); net_status(out, listen(fd, SOMAXCONN)); }
void tarn_rt_net_accept(TarnNetRaw *out, int32_t fd) { net_init(out); net_status(out, accept(fd, NULL, NULL)); if (!out->code) net_trace("open", (int)out->value); }
void tarn_rt_net_connect(TarnNetRaw *out, int32_t fd, const TarnNetAddr *address) {
    net_init(out); struct sockaddr_storage sa; socklen_t len;
    if (net_native(address, &sa, &len) < 0) { out->code = errno; return; }
    net_status(out, connect(fd, (struct sockaddr *)&sa, len));
}
void tarn_rt_net_read(TarnNetRaw *out, int32_t fd, uint8_t *bytes, uint64_t len) {
    net_init(out); if (len) net_status(out, recv(fd, bytes, len, 0));
}
void tarn_rt_net_write(TarnNetRaw *out, int32_t fd, const uint8_t *bytes, uint64_t len) { net_init(out); net_status(out, send(fd, bytes, len, MSG_NOSIGNAL)); }
void tarn_rt_net_recv(TarnNetRaw *out, int32_t fd, uint8_t *bytes, uint64_t len) {
    net_init(out); struct sockaddr_storage sa; socklen_t size = sizeof(sa);
    net_status(out, recvfrom(fd, bytes, len, 0, (struct sockaddr *)&sa, &size));
    if (!out->code) net_address(&out->address, (struct sockaddr *)&sa);
}
void tarn_rt_net_send(TarnNetRaw *out, int32_t fd, const uint8_t *bytes, uint64_t len, const TarnNetAddr *address) {
    net_init(out); struct sockaddr_storage sa; socklen_t size;
    if (net_native(address, &sa, &size) < 0) { out->code = errno; return; }
    net_status(out, sendto(fd, bytes, len, MSG_NOSIGNAL, (struct sockaddr *)&sa, size));
}
void tarn_rt_net_addr(TarnNetRaw *out, int32_t fd, uint8_t peer) {
    net_init(out); struct sockaddr_storage sa; socklen_t size = sizeof(sa);
    net_status(out, peer ? getpeername(fd, (struct sockaddr *)&sa, &size) : getsockname(fd, (struct sockaddr *)&sa, &size));
    if (!out->code) net_address(&out->address, (struct sockaddr *)&sa);
}
void tarn_rt_net_shutdown(TarnNetRaw *out, int32_t fd, int32_t how) { net_init(out); net_status(out, shutdown(fd, how)); }
void tarn_rt_net_close(TarnNetRaw *out, int32_t fd) {
    /* Observe the release attempt before close makes fd reusable by another
     * task. Logging after close can misorder reuse and falsely report two owners.
     * This is only test observation; the syscall remains the actual release. */
    net_trace("close", fd);
    net_init(out); net_status(out, close(fd));
    if (out->code == EBADF) abort(); /* impossible with a verified live owner */
    /* Linux consumes fd even when close reports EINTR: never retry. */
}
void tarn_rt_net_drop(int32_t fd) { TarnNetRaw out; tarn_rt_net_close(&out, fd); }

void tarn_rt_net_main_error(uint32_t kind, int32_t code) {
    static const char *names[] = {"address in use", "connection refused", "connection reset", "broken pipe", "timed out", "would block", "invalid address", "DNS failure", "other OS error", "write made no progress"};
    if (kind >= sizeof(names) / sizeof(names[0])) abort();
    fprintf(stderr, "network error: %s (native code %" PRId32 ")\n", names[kind], code);
}

/* Phase 12B: no application pointers survive any of these calls. */
#include <sys/epoll.h>
#include <fcntl.h>
#include <time.h>
#ifndef SO_COOKIE
#define SO_COOKIE 57
#endif
/* Poll bookkeeping does not own sockets. Cookie checks prevent fd reuse from
   turning an old token into modification/deletion authority over a new socket. */
typedef struct TarnRegistration {
    int fd;
    uint64_t cookie, token;
    struct TarnRegistration *next;
} TarnRegistration;
typedef struct { int fd; TarnRegistration *head; } TarnPoll;
typedef struct { uint64_t token; uint8_t readable, writable, error, hangup; uint8_t padding[4]; } TarnEvent;
_Static_assert(sizeof(TarnEvent) == 16 && offsetof(TarnEvent, hangup) == 11, "event ABI");
static _Atomic uint64_t net_next_token = 1;
void tarn_rt_net_nonblocking(TarnNetRaw *out, int32_t fd, uint8_t enabled) {
    net_init(out);
    int mode = fcntl(fd, F_GETFL);
    if (mode < 0) { out->code = errno; return; }
    net_status(out, fcntl(fd, F_SETFL, enabled ? mode | O_NONBLOCK : mode & ~O_NONBLOCK));
}
void tarn_rt_net_mode(TarnNetRaw *out, int32_t fd) {
    net_init(out); int mode = fcntl(fd, F_GETFL);
    if (mode < 0) out->code = errno; else out->value = !!(mode & O_NONBLOCK);
}
void tarn_rt_net_connected(TarnNetRaw *out, int32_t fd) {
    net_init(out); int error = 0; socklen_t n = sizeof(error);
    if (getsockopt(fd, SOL_SOCKET, SO_ERROR, &error, &n) < 0) { out->code = errno; return; }
    if (error) { out->code = error; return; }
    struct sockaddr_storage peer; n = sizeof(peer);
    if (getpeername(fd, (struct sockaddr *)&peer, &n) < 0) out->code = errno == ENOTCONN ? EAGAIN : errno;
}
void tarn_rt_net_now(TarnNetRaw *out) {
    net_init(out); struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) < 0) out->code = errno;
    else out->value = (int64_t)now.tv_sec * 1000 + now.tv_nsec / 1000000;
}
void tarn_rt_net_poll_new(TarnNetRaw *out) {
    net_init(out); int fd = epoll_create1(EPOLL_CLOEXEC);
    if (fd < 0) { out->code = errno; return; }
    TarnPoll *poll = malloc(sizeof(*poll));
    if (!poll) { int error = ENOMEM; close(fd); out->code = error; return; }
    poll->fd = fd; poll->head = NULL; out->value = (int64_t)(uintptr_t)poll;
    net_trace("open", fd);
}
void tarn_rt_net_poll_ctl(TarnNetRaw *out, TarnPoll *poll, int32_t fd, int32_t operation, int32_t interest, uint64_t token) {
    net_init(out); uint64_t cookie; socklen_t n = sizeof(cookie);
    if (operation < 0 || operation > 2 || interest < 1 || interest > 3) { out->code = EINVAL; return; }
    if (getsockopt(fd, SOL_SOCKET, SO_COOKIE, &cookie, &n) < 0) { out->code = errno; return; }
    TarnRegistration **link = &poll->head;
    while (*link && (*link)->fd != fd) link = &(*link)->next;
    TarnRegistration *record = *link;
    if (operation && (!record || record->token != token || record->cookie != cookie)) { out->code = ENOENT; return; }
    if (!operation && record && record->cookie == cookie) { out->code = EEXIST; return; }
    TarnRegistration *fresh = NULL;
    if (!operation) {
        fresh = malloc(sizeof(*fresh));
        if (!fresh) { out->code = ENOMEM; return; }
        /* Never wrap or reuse. Signed raw value preserves checked u64 conversion. */
        token = atomic_load(&net_next_token);
        for (;;) {
            if (token >= INT64_MAX) { free(fresh); out->code = EOVERFLOW; return; }
            if (atomic_compare_exchange_weak(&net_next_token, &token, token + 1)) break;
        }
    }
    struct epoll_event event = {0};
    event.events = EPOLLRDHUP | ((interest & 1) ? EPOLLIN : 0) | ((interest & 2) ? EPOLLOUT : 0);
    event.data.u64 = token;
    int op = operation == 0 ? EPOLL_CTL_ADD : operation == 1 ? EPOLL_CTL_MOD : EPOLL_CTL_DEL;
    if (epoll_ctl(poll->fd, op, fd, &event) < 0) { out->code = errno; free(fresh); return; }
    if (!operation) {
        fresh->fd = fd; fresh->cookie = cookie; fresh->token = token;
        fresh->next = record ? record->next : NULL; *link = fresh; free(record);
    } else if (operation == 2) { *link = record->next; free(record); }
    out->value = (int64_t)token;
}
void tarn_rt_net_poll_wait(TarnNetRaw *out, TarnPoll *poll, TarnEvent *events, uint64_t length, int32_t timeout) {
    net_init(out);
    if (!length || timeout < -1) { out->code = EINVAL; return; }
    struct epoll_event native[64];
    int count = epoll_wait(poll->fd, native, length < 64 ? (int)length : 64, timeout);
    if (count < 0) { out->code = errno; return; }
    for (int i = 0; i < count; ++i) {
        memset(&events[i], 0, sizeof(events[i]));
        events[i].token = native[i].data.u64;
        events[i].readable = !!(native[i].events & EPOLLIN);
        events[i].writable = !!(native[i].events & EPOLLOUT);
        events[i].error = !!(native[i].events & EPOLLERR);
        events[i].hangup = !!(native[i].events & (EPOLLHUP | EPOLLRDHUP));
    }
    out->value = count;
}
void tarn_rt_net_close_poll(TarnNetRaw *out, TarnPoll *poll) {
    tarn_rt_net_close(out, poll->fd);
    while (poll->head) { TarnRegistration *record = poll->head; poll->head = record->next; free(record); }
    free(poll);
}
void tarn_rt_net_poll_drop(TarnPoll *poll) { TarnNetRaw out; tarn_rt_net_close_poll(&out, poll); }
