/* Tarn internal runtime ABI v0: Linux x86_64, System V C ABI. */
#define _POSIX_C_SOURCE 200809L
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <math.h>

typedef struct { uint64_t len; unsigned char bytes[]; } TarnString;
/* Owned string pointers are unique. Literals allocate; moves transfer ownership. */
TarnString *tarn_rt_string(const unsigned char *data, uint64_t len) {
    if (len > SIZE_MAX - sizeof(TarnString)) abort();
    TarnString *s = malloc(sizeof(TarnString) + len);
    if (!s) abort();
    s->len = len;
    memcpy(s->bytes, data, len);
    return s;
}
void tarn_rt_drop_string(TarnString *s) {
    /* Opt-in compiler test observation, never a user destructor hook. */
    if (getenv("TARN_TRACE_DROPS")) { flockfile(stderr); fputs("drop:", stderr); fwrite(s->bytes, 1, s->len, stderr); fputc('\n', stderr); funlockfile(stderr); }
    free(s);
}
void tarn_rt_print_i64(int64_t v) { printf("%" PRId64 "\n", v); }
void tarn_rt_print_u64(uint64_t v) { printf("%" PRIu64 "\n", v); }
void tarn_rt_print_f64(double v) { printf("%.17g\n", v); }
void tarn_rt_print_bool(uint8_t v) { puts(v ? "true" : "false"); }
void tarn_rt_print_string(const TarnString *s) { fwrite(s->bytes, 1, s->len, stdout); fputc('\n', stdout); }
_Noreturn void tarn_rt_panic(const TarnString *s) {
    fputs("panic: ", stderr); fwrite(s->bytes, 1, s->len, stderr); fputc('\n', stderr); fflush(NULL); abort();
}
_Noreturn void tarn_rt_fault(void) { fputs("panic: checked arithmetic or bounds failure\n", stderr); fflush(NULL); abort(); }

float tarn_rt_rem_f32(float a, float b) { return fmodf(a, b); }
double tarn_rt_rem_f64(double a, double b) { return fmod(a, b); }

/* A closure environment header holds an internal, compiler-generated thunk.
 * Borrowed stack environments use a null thunk. Destruction and consumption
 * bodies are post-drop functions; their thunk releases owned storage. */
void *tarn_rt_env_alloc(uint64_t size) {
    void *p = malloc((size_t)size);
    if (!p) abort();
    return p;
}
void tarn_rt_env_free(void *p) { free(p); }
void tarn_rt_env_drop(void *p) {
    if (!p) return;
    void (*drop)(void *);
    memcpy(&drop, p, sizeof(drop));
    if (drop) drop(p);
}

/* Private 11A task ABI. Worker/result adapters are generated by the compiler;
 * this record has no knowledge of Tarn types or resource layouts. */
#include <pthread.h>
typedef void (*TarnTaskWorker)(void *, void *, void *);
typedef void (*TarnTaskResultDrop)(void *);
typedef struct {
    pthread_t thread;
    TarnTaskWorker worker;
    TarnTaskResultDrop drop_result;
    void *code;
    void *environment;
    void *result;
    unsigned initialized;
    unsigned joined;
} TarnTask;

static _Noreturn void tarn_task_fault(void) {
    fputs("panic: native task runtime fault\n", stderr);
    fflush(NULL);
    abort();
}

static void *tarn_task_entry(void *argument) {
    TarnTask *task = argument;
    task->worker(task->result, task->code, task->environment);
    task->initialized = 1;
    return NULL;
}

TarnTask *tarn_rt_task_spawn(TarnTaskWorker worker, TarnTaskResultDrop drop_result,
                           uint64_t result_size, void *code, void *environment) {
    if (!worker || !drop_result || result_size > 65536) tarn_task_fault();
    TarnTask *task = calloc(1, sizeof(*task));
    if (!task) tarn_task_fault();
    task->result = calloc(1, result_size ? (size_t)result_size : 1);
    if (!task->result) tarn_task_fault();
    task->worker = worker;
    task->drop_result = drop_result;
    task->code = code;
    task->environment = environment;
    if (pthread_create(&task->thread, NULL, tarn_task_entry, task)) tarn_task_fault();
    return task;
}

/* Borrowed result storage, valid until release; ownership transfers only when
 * generated join code moves its initialized value into caller storage. */
void *tarn_rt_task_wait(TarnTask *task) {
    if (!task || task->joined || pthread_equal(task->thread, pthread_self())) tarn_task_fault();
    if (pthread_join(task->thread, NULL)) tarn_task_fault();
    task->joined = 1;
    if (!task->initialized) tarn_task_fault();
    return task->result;
}

/* Called only after generated code has moved the result out. */
void tarn_rt_task_release(TarnTask *task) {
    if (!task || !task->joined || !task->initialized) tarn_task_fault();
    task->initialized = 0;
    free(task->result);
    free(task);
}

void tarn_rt_task_drop(TarnTask *task) {
    void *result = tarn_rt_task_wait(task);
    task->drop_result(result);
    tarn_rt_task_release(task);
}
