use tarn_diagnostics::Span;

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    /// 1-based line of `span.start`.
    pub line: u32,
    /// 1-based column (in Unicode scalar values) of `span.start`.
    pub column: u32,
}

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Ident(String),
    /// Value of a decimal, hex, octal or binary literal.
    Int(u64),
    /// Source text of the literal with `_` removed (parsed later, keeps `Eq`-free value out of the lexer).
    Float(String),
    /// Cooked string value (escapes resolved).
    Str(String),

    // Keywords.
    Fn,
    Return,
    If,
    Else,
    For,
    In,
    Break,
    Continue,
    Match,
    Struct,
    Enum,
    Interface,
    Impl,
    Copy,
    Var,
    Pub,
    Import,
    True,
    False,
    Try,
    Spawn,
    Unsafe,
    Extern,
    Mut,

    // Delimiters.
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,

    // Punctuation and operators.
    Comma,
    Colon,
    Dot,
    DotDot,
    DotDotEq,
    Eq,
    ColonEq,
    Arrow,
    FatArrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Bang,
    EqEq,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Shl,
    Shr,

    /// Statement terminator inserted at a line break (see ADR 0003).
    Newline,
    Eof,
}

pub fn keyword(ident: &str) -> Option<TokenKind> {
    use TokenKind::*;
    Some(match ident {
        "fn" => Fn,
        "return" => Return,
        "if" => If,
        "else" => Else,
        "for" => For,
        "in" => In,
        "break" => Break,
        "continue" => Continue,
        "match" => Match,
        "struct" => Struct,
        "enum" => Enum,
        "interface" => Interface,
        "impl" => Impl,
        "copy" => Copy,
        "var" => Var,
        "pub" => Pub,
        "import" => Import,
        "true" => True,
        "false" => False,
        "try" => Try,
        "spawn" => Spawn,
        "unsafe" => Unsafe,
        "extern" => Extern,
        "mut" => Mut,
        _ => return None,
    })
}

impl TokenKind {
    /// Short stable name, used by `tarn lex` and in tests.
    pub fn name(&self) -> &'static str {
        use TokenKind::*;
        match self {
            Ident(_) => "ident",
            Int(_) => "int",
            Float(_) => "float",
            Str(_) => "string",
            Fn => "fn",
            Return => "return",
            If => "if",
            Else => "else",
            For => "for",
            In => "in",
            Break => "break",
            Continue => "continue",
            Match => "match",
            Struct => "struct",
            Enum => "enum",
            Interface => "interface",
            Impl => "impl",
            Copy => "copy",
            Var => "var",
            Pub => "pub",
            Import => "import",
            True => "true",
            False => "false",
            Try => "try",
            Spawn => "spawn",
            Unsafe => "unsafe",
            Extern => "extern",
            Mut => "mut",
            LParen => "(",
            RParen => ")",
            LBrace => "{",
            RBrace => "}",
            LBracket => "[",
            RBracket => "]",
            Comma => ",",
            Colon => ":",
            Dot => ".",
            DotDot => "..",
            DotDotEq => "..=",
            Eq => "=",
            ColonEq => ":=",
            Arrow => "->",
            FatArrow => "=>",
            Plus => "+",
            Minus => "-",
            Star => "*",
            Slash => "/",
            Percent => "%",
            Amp => "&",
            AmpAmp => "&&",
            Pipe => "|",
            PipePipe => "||",
            Caret => "^",
            Bang => "!",
            EqEq => "==",
            BangEq => "!=",
            Lt => "<",
            LtEq => "<=",
            Gt => ">",
            GtEq => ">=",
            Shl => "<<",
            Shr => ">>",
            Newline => "newline",
            Eof => "eof",
        }
    }
}
