[package]
name = "tarn_driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tarn_ast = { path = "../ast" }
tarn_diagnostics = { path = "../diagnostics" }
tarn_parser = { path = "../parser" }
tarn_resolve = { path = "../resolve" }
tarn_types = { path = "../types" }
tarn_ir = { path = "../ir" }
tarn_ownership = { path = "../ownership" }

[dev-dependencies]
