[package]
name = "tarn_backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tarn_ir = { path = "../ir" }
tarn_types = { path = "../types" }
tarn_resolve = { path = "../resolve" }
cranelift-codegen = { version = "=0.125.3", default-features = false, features = ["std", "host-arch"] }
cranelift-frontend = "=0.125.3"
cranelift-module = "=0.125.3"
cranelift-object = "=0.125.3"
cranelift-native = "=0.125.3"

[dev-dependencies]
tarn_driver = { path = "../driver" }
